name: Deploy MLflow projet
run-name: Build and Deploy
on:
  push:
    branches:
      - master
      - dev
      - releases/**
    tags:
      - v2
      - v1.*
  pull_request:
    branches: [ master ]
permissions: read-all
jobs:
  test_unit:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9"] #, "3.10", "3.11", "pypy3.9", "pypy3.10"]
        exclude:
          - os: macos-latest
            python-version: "3.9"
          - os: windows-latest
            python-version: "3.9"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Upgrade pip
      run: python -m pip install --upgrade pip 
    - name: Install requirements
      run: |
        pip install -r test_requirements.txt
    - name: Run unit test
      run: |
        pytest test.py                  # --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # hermannsiebenou 
          password: ${{ secrets.DOCKERHUB_TOKEN }} #19mboeboO 
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: hermannsiebenou/model-ml:latest