name: Deploy MLflow projet
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on:
  push:
    branches:
      - master
      - dev
      - releases/**
    tags:
      - v2
      - v1.*
permissions: read-all
jobs:
  Install_package:
    runs-on: linux #{{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: linux #{{ matrix.version }}
          cache: 'pip'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
