name: linting
run-name: Run linting
on:
  push:
    branches:
      - master

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install dependencies for linting
      run: |
        if [ -f lint_requirements.txt ]; then pip install -r lint_requirements.txt; fi
    - name: Run flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run mypy
      run: |
        echo "mypy --install-types"
        echo "mypy src/"
    - name: Run isort
      run: isort .
